version: '3'
services:
  redisearch:
    image: redislabs/redisearch:2.2.7
    ports: 
      - 6379:6379
    networks:
      default:
        ipv4_address: 172.24.0.100
  mock:
    build:
      context: .
      dockerfile: cmd/mock/Dockerfile
    networks:
      default:
        ipv4_address: 172.24.0.101
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/24
        gateway: 172.24.0.1