// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: krkstops-grpc/krk-stops.proto

package krk_stops

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Installation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Installation) Reset() {
	*x = Installation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Installation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Installation) ProtoMessage() {}

func (x *Installation) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Installation.ProtoReflect.Descriptor instead.
func (*Installation) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{0}
}

func (x *Installation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Installation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Installation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Airly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caqi        int32   `protobuf:"varint,1,opt,name=caqi,proto3" json:"caqi,omitempty"`
	Color       string  `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Humidity    int32   `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Temperature float32 `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *Airly) Reset() {
	*x = Airly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Airly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airly) ProtoMessage() {}

func (x *Airly) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airly.ProtoReflect.Descriptor instead.
func (*Airly) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{1}
}

func (x *Airly) GetCaqi() int32 {
	if x != nil {
		return x.Caqi
	}
	return 0
}

func (x *Airly) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Airly) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Airly) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type InstallationLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *InstallationLocation) Reset() {
	*x = InstallationLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallationLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallationLocation) ProtoMessage() {}

func (x *InstallationLocation) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallationLocation.ProtoReflect.Descriptor instead.
func (*InstallationLocation) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{2}
}

func (x *InstallationLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *InstallationLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Departure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelativeTime       int32  `protobuf:"varint,1,opt,name=relativeTime,proto3" json:"relativeTime,omitempty"`
	PlannedTime        string `protobuf:"bytes,2,opt,name=plannedTime,proto3" json:"plannedTime,omitempty"`
	Direction          string `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	PatternText        string `protobuf:"bytes,4,opt,name=patternText,proto3" json:"patternText,omitempty"`
	Color              uint32 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	RelativeTimeParsed string `protobuf:"bytes,6,opt,name=relativeTimeParsed,proto3" json:"relativeTimeParsed,omitempty"`
}

func (x *Departure) Reset() {
	*x = Departure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Departure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departure) ProtoMessage() {}

func (x *Departure) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departure.ProtoReflect.Descriptor instead.
func (*Departure) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{3}
}

func (x *Departure) GetRelativeTime() int32 {
	if x != nil {
		return x.RelativeTime
	}
	return 0
}

func (x *Departure) GetPlannedTime() string {
	if x != nil {
		return x.PlannedTime
	}
	return ""
}

func (x *Departure) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Departure) GetPatternText() string {
	if x != nil {
		return x.PatternText
	}
	return ""
}

func (x *Departure) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Departure) GetRelativeTimeParsed() string {
	if x != nil {
		return x.RelativeTimeParsed
	}
	return ""
}

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortName string `protobuf:"bytes,1,opt,name=shortName,proto3" json:"shortName,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{4}
}

func (x *Stop) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Stop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *StopSearch) Reset() {
	*x = StopSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSearch) ProtoMessage() {}

func (x *StopSearch) ProtoReflect() protoreflect.Message {
	mi := &file_krkstops_grpc_krk_stops_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSearch.ProtoReflect.Descriptor instead.
func (*StopSearch) Descriptor() ([]byte, []int) {
	return file_krkstops_grpc_krk_stops_proto_rawDescGZIP(), []int{5}
}

func (x *StopSearch) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_krkstops_grpc_krk_stops_proto protoreflect.FileDescriptor

var file_krkstops_grpc_krk_stops_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6b, 0x72, 0x6b, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x6b, 0x72, 0x6b, 0x2d, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x58, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x6f, 0x0a, 0x05, 0x41, 0x69, 0x72,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x71, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x61, 0x71, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0xd7, 0x01, 0x0a,
	0x09, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x22, 0x38, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x22, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x32, 0xfe, 0x01, 0x0a, 0x08, 0x4b, 0x72, 0x6b, 0x53, 0x74, 0x6f, 0x70,
	0x73, 0x12, 0x23, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x12, 0x0d, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x06, 0x2e, 0x41,
	0x69, 0x72, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x65,
	0x61, 0x72, 0x65, 0x73, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x05, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x0a,
	0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x25,
	0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x0b, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x05, 0x2e, 0x53, 0x74, 0x6f,
	0x70, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_krkstops_grpc_krk_stops_proto_rawDescOnce sync.Once
	file_krkstops_grpc_krk_stops_proto_rawDescData = file_krkstops_grpc_krk_stops_proto_rawDesc
)

func file_krkstops_grpc_krk_stops_proto_rawDescGZIP() []byte {
	file_krkstops_grpc_krk_stops_proto_rawDescOnce.Do(func() {
		file_krkstops_grpc_krk_stops_proto_rawDescData = protoimpl.X.CompressGZIP(file_krkstops_grpc_krk_stops_proto_rawDescData)
	})
	return file_krkstops_grpc_krk_stops_proto_rawDescData
}

var file_krkstops_grpc_krk_stops_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_krkstops_grpc_krk_stops_proto_goTypes = []interface{}{
	(*Installation)(nil),         // 0: Installation
	(*Airly)(nil),                // 1: Airly
	(*InstallationLocation)(nil), // 2: InstallationLocation
	(*Departure)(nil),            // 3: Departure
	(*Stop)(nil),                 // 4: Stop
	(*StopSearch)(nil),           // 5: StopSearch
}
var file_krkstops_grpc_krk_stops_proto_depIdxs = []int32{
	0, // 0: KrkStops.GetAirly:input_type -> Installation
	2, // 1: KrkStops.FindNearestAirlyInstallation:input_type -> InstallationLocation
	0, // 2: KrkStops.GetAirlyInstallation:input_type -> Installation
	4, // 3: KrkStops.GetDepartures:input_type -> Stop
	5, // 4: KrkStops.SearchStops:input_type -> StopSearch
	1, // 5: KrkStops.GetAirly:output_type -> Airly
	0, // 6: KrkStops.FindNearestAirlyInstallation:output_type -> Installation
	0, // 7: KrkStops.GetAirlyInstallation:output_type -> Installation
	3, // 8: KrkStops.GetDepartures:output_type -> Departure
	4, // 9: KrkStops.SearchStops:output_type -> Stop
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_krkstops_grpc_krk_stops_proto_init() }
func file_krkstops_grpc_krk_stops_proto_init() {
	if File_krkstops_grpc_krk_stops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_krkstops_grpc_krk_stops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Installation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krkstops_grpc_krk_stops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Airly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krkstops_grpc_krk_stops_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallationLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krkstops_grpc_krk_stops_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Departure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krkstops_grpc_krk_stops_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krkstops_grpc_krk_stops_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_krkstops_grpc_krk_stops_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_krkstops_grpc_krk_stops_proto_goTypes,
		DependencyIndexes: file_krkstops_grpc_krk_stops_proto_depIdxs,
		MessageInfos:      file_krkstops_grpc_krk_stops_proto_msgTypes,
	}.Build()
	File_krkstops_grpc_krk_stops_proto = out.File
	file_krkstops_grpc_krk_stops_proto_rawDesc = nil
	file_krkstops_grpc_krk_stops_proto_goTypes = nil
	file_krkstops_grpc_krk_stops_proto_depIdxs = nil
}
