// Code generated by protoc-gen-go. DO NOT EDIT.
// source: krkstops-grpc/krk-stops.proto

package krk_stops

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Installation struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Installation) Reset()         { *m = Installation{} }
func (m *Installation) String() string { return proto.CompactTextString(m) }
func (*Installation) ProtoMessage()    {}
func (*Installation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127bf6ac452d96e, []int{0}
}

func (m *Installation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Installation.Unmarshal(m, b)
}
func (m *Installation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Installation.Marshal(b, m, deterministic)
}
func (m *Installation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Installation.Merge(m, src)
}
func (m *Installation) XXX_Size() int {
	return xxx_messageInfo_Installation.Size(m)
}
func (m *Installation) XXX_DiscardUnknown() {
	xxx_messageInfo_Installation.DiscardUnknown(m)
}

var xxx_messageInfo_Installation proto.InternalMessageInfo

func (m *Installation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Airly struct {
	Caqi                 int32    `protobuf:"varint,1,opt,name=caqi,proto3" json:"caqi,omitempty"`
	Color                string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Humidity             int32    `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Temperature          float32  `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Airly) Reset()         { *m = Airly{} }
func (m *Airly) String() string { return proto.CompactTextString(m) }
func (*Airly) ProtoMessage()    {}
func (*Airly) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127bf6ac452d96e, []int{1}
}

func (m *Airly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Airly.Unmarshal(m, b)
}
func (m *Airly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Airly.Marshal(b, m, deterministic)
}
func (m *Airly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Airly.Merge(m, src)
}
func (m *Airly) XXX_Size() int {
	return xxx_messageInfo_Airly.Size(m)
}
func (m *Airly) XXX_DiscardUnknown() {
	xxx_messageInfo_Airly.DiscardUnknown(m)
}

var xxx_messageInfo_Airly proto.InternalMessageInfo

func (m *Airly) GetCaqi() int32 {
	if m != nil {
		return m.Caqi
	}
	return 0
}

func (m *Airly) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Airly) GetHumidity() int32 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *Airly) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type Departure struct {
	RelativeTime         int32    `protobuf:"varint,1,opt,name=relativeTime,proto3" json:"relativeTime,omitempty"`
	PlannedTime          string   `protobuf:"bytes,2,opt,name=plannedTime,proto3" json:"plannedTime,omitempty"`
	Direction            string   `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	PatternText          string   `protobuf:"bytes,4,opt,name=patternText,proto3" json:"patternText,omitempty"`
	Color                string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	RelativeTimeParsed   string   `protobuf:"bytes,6,opt,name=relativeTimeParsed,proto3" json:"relativeTimeParsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Departure) Reset()         { *m = Departure{} }
func (m *Departure) String() string { return proto.CompactTextString(m) }
func (*Departure) ProtoMessage()    {}
func (*Departure) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127bf6ac452d96e, []int{2}
}

func (m *Departure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Departure.Unmarshal(m, b)
}
func (m *Departure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Departure.Marshal(b, m, deterministic)
}
func (m *Departure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Departure.Merge(m, src)
}
func (m *Departure) XXX_Size() int {
	return xxx_messageInfo_Departure.Size(m)
}
func (m *Departure) XXX_DiscardUnknown() {
	xxx_messageInfo_Departure.DiscardUnknown(m)
}

var xxx_messageInfo_Departure proto.InternalMessageInfo

func (m *Departure) GetRelativeTime() int32 {
	if m != nil {
		return m.RelativeTime
	}
	return 0
}

func (m *Departure) GetPlannedTime() string {
	if m != nil {
		return m.PlannedTime
	}
	return ""
}

func (m *Departure) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *Departure) GetPatternText() string {
	if m != nil {
		return m.PatternText
	}
	return ""
}

func (m *Departure) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Departure) GetRelativeTimeParsed() string {
	if m != nil {
		return m.RelativeTimeParsed
	}
	return ""
}

type Stop struct {
	ShortName            string   `protobuf:"bytes,1,opt,name=shortName,proto3" json:"shortName,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop) Reset()         { *m = Stop{} }
func (m *Stop) String() string { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()    {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127bf6ac452d96e, []int{3}
}

func (m *Stop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop.Unmarshal(m, b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return xxx_messageInfo_Stop.Size(m)
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

func (m *Stop) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Stop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StopSearch struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSearch) Reset()         { *m = StopSearch{} }
func (m *StopSearch) String() string { return proto.CompactTextString(m) }
func (*StopSearch) ProtoMessage()    {}
func (*StopSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127bf6ac452d96e, []int{4}
}

func (m *StopSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSearch.Unmarshal(m, b)
}
func (m *StopSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSearch.Marshal(b, m, deterministic)
}
func (m *StopSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSearch.Merge(m, src)
}
func (m *StopSearch) XXX_Size() int {
	return xxx_messageInfo_StopSearch.Size(m)
}
func (m *StopSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSearch.DiscardUnknown(m)
}

var xxx_messageInfo_StopSearch proto.InternalMessageInfo

func (m *StopSearch) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*Installation)(nil), "Installation")
	proto.RegisterType((*Airly)(nil), "Airly")
	proto.RegisterType((*Departure)(nil), "Departure")
	proto.RegisterType((*Stop)(nil), "Stop")
	proto.RegisterType((*StopSearch)(nil), "StopSearch")
}

func init() { proto.RegisterFile("krkstops-grpc/krk-stops.proto", fileDescriptor_d127bf6ac452d96e) }

var fileDescriptor_d127bf6ac452d96e = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6a, 0xe3, 0x30,
	0x14, 0x8c, 0xbd, 0x71, 0x88, 0x5f, 0x92, 0x3d, 0x88, 0x3d, 0x18, 0xb3, 0xbb, 0x18, 0x95, 0x96,
	0x5c, 0xe2, 0x96, 0xf6, 0xd2, 0x6b, 0xa1, 0x10, 0x4a, 0xa1, 0x14, 0x27, 0x3f, 0xa0, 0xda, 0x8f,
	0x46, 0xd8, 0xb1, 0x9c, 0x67, 0xa5, 0x34, 0x97, 0xfe, 0x66, 0x7f, 0xa7, 0x48, 0x36, 0xb6, 0x0b,
	0xbd, 0x69, 0x46, 0x33, 0xd2, 0x8c, 0x9e, 0xe0, 0x5f, 0x4e, 0x79, 0xad, 0x55, 0x55, 0xaf, 0x5e,
	0xa9, 0x4a, 0x2f, 0x73, 0xca, 0x57, 0x16, 0xc6, 0x15, 0x29, 0xad, 0xf8, 0x7f, 0x98, 0x3f, 0x94,
	0xb5, 0x16, 0x45, 0x21, 0xb4, 0x54, 0x25, 0xfb, 0x0d, 0xae, 0xcc, 0x02, 0x27, 0x72, 0x96, 0x5e,
	0xe2, 0xca, 0x8c, 0x2b, 0xf0, 0xee, 0x24, 0x15, 0x27, 0xc6, 0x60, 0x9c, 0x8a, 0x83, 0x6c, 0xb7,
	0xec, 0x9a, 0xfd, 0x01, 0x2f, 0x55, 0x85, 0xa2, 0xc0, 0x8d, 0x9c, 0xa5, 0x9f, 0x34, 0x80, 0x85,
	0x30, 0xdd, 0x1d, 0xf7, 0x32, 0x93, 0xfa, 0x14, 0xfc, 0xb2, 0xea, 0x0e, 0xb3, 0x08, 0x66, 0x1a,
	0xf7, 0x15, 0x92, 0xd0, 0x47, 0xc2, 0x60, 0x1c, 0x39, 0x4b, 0x37, 0x19, 0x52, 0xfc, 0xd3, 0x01,
	0xff, 0x1e, 0x2b, 0x41, 0x06, 0x31, 0x0e, 0x73, 0x42, 0x13, 0xed, 0x0d, 0xb7, 0x72, 0x8f, 0xed,
	0xed, 0xdf, 0x38, 0x73, 0x66, 0x55, 0x88, 0xb2, 0xc4, 0xcc, 0x4a, 0x9a, 0x2c, 0x43, 0x8a, 0xfd,
	0x05, 0x3f, 0x93, 0x84, 0xa9, 0x69, 0x68, 0x23, 0xf9, 0x49, 0x4f, 0x58, 0xbf, 0xd0, 0x1a, 0xa9,
	0xdc, 0xe2, 0xbb, 0xb6, 0x99, 0x8c, 0xbf, 0xa7, 0xfa, 0x9e, 0xde, 0xb0, 0x67, 0x0c, 0x6c, 0x98,
	0xe3, 0x59, 0x50, 0x8d, 0x59, 0x30, 0xb1, 0x92, 0x1f, 0x76, 0xf8, 0x2d, 0x8c, 0x37, 0x5a, 0x55,
	0x26, 0x4d, 0xbd, 0x53, 0xa4, 0x9f, 0x44, 0x5b, 0xc8, 0x4f, 0x7a, 0xc2, 0xbc, 0x73, 0x29, 0xba,
	0x1a, 0x76, 0xcd, 0x39, 0x80, 0x71, 0x6e, 0x50, 0x50, 0xba, 0x33, 0x69, 0x0e, 0x47, 0xa4, 0x53,
	0xeb, 0x6d, 0xc0, 0xf5, 0x07, 0x4c, 0x1f, 0x29, 0x37, 0xb2, 0x9a, 0x9d, 0xc1, 0x74, 0x8d, 0xba,
	0x99, 0xdb, 0x22, 0x1e, 0xce, 0x37, 0x9c, 0xc4, 0x96, 0xe6, 0x23, 0x76, 0x01, 0x8b, 0x35, 0xea,
	0xee, 0xa9, 0x6b, 0xe6, 0xc5, 0xc6, 0x1d, 0x42, 0xdc, 0x71, 0x7c, 0x74, 0xe5, 0xb0, 0x73, 0x98,
	0x35, 0x17, 0x37, 0x67, 0xcf, 0xe2, 0x3e, 0x4a, 0xd8, 0x58, 0x8c, 0xec, 0x65, 0x62, 0xff, 0xd3,
	0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x2b, 0xc1, 0xf3, 0x70, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KrkStopsClient is the client API for KrkStops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KrkStopsClient interface {
	GetAirly(ctx context.Context, in *Installation, opts ...grpc.CallOption) (*Airly, error)
	GetDepartures(ctx context.Context, in *Stop, opts ...grpc.CallOption) (KrkStops_GetDeparturesClient, error)
	SearchStops(ctx context.Context, in *StopSearch, opts ...grpc.CallOption) (KrkStops_SearchStopsClient, error)
}

type krkStopsClient struct {
	cc grpc.ClientConnInterface
}

func NewKrkStopsClient(cc grpc.ClientConnInterface) KrkStopsClient {
	return &krkStopsClient{cc}
}

func (c *krkStopsClient) GetAirly(ctx context.Context, in *Installation, opts ...grpc.CallOption) (*Airly, error) {
	out := new(Airly)
	err := c.cc.Invoke(ctx, "/KrkStops/GetAirly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *krkStopsClient) GetDepartures(ctx context.Context, in *Stop, opts ...grpc.CallOption) (KrkStops_GetDeparturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KrkStops_serviceDesc.Streams[0], "/KrkStops/GetDepartures", opts...)
	if err != nil {
		return nil, err
	}
	x := &krkStopsGetDeparturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KrkStops_GetDeparturesClient interface {
	Recv() (*Departure, error)
	grpc.ClientStream
}

type krkStopsGetDeparturesClient struct {
	grpc.ClientStream
}

func (x *krkStopsGetDeparturesClient) Recv() (*Departure, error) {
	m := new(Departure)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *krkStopsClient) SearchStops(ctx context.Context, in *StopSearch, opts ...grpc.CallOption) (KrkStops_SearchStopsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KrkStops_serviceDesc.Streams[1], "/KrkStops/SearchStops", opts...)
	if err != nil {
		return nil, err
	}
	x := &krkStopsSearchStopsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KrkStops_SearchStopsClient interface {
	Recv() (*Stop, error)
	grpc.ClientStream
}

type krkStopsSearchStopsClient struct {
	grpc.ClientStream
}

func (x *krkStopsSearchStopsClient) Recv() (*Stop, error) {
	m := new(Stop)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KrkStopsServer is the server API for KrkStops service.
type KrkStopsServer interface {
	GetAirly(context.Context, *Installation) (*Airly, error)
	GetDepartures(*Stop, KrkStops_GetDeparturesServer) error
	SearchStops(*StopSearch, KrkStops_SearchStopsServer) error
}

// UnimplementedKrkStopsServer can be embedded to have forward compatible implementations.
type UnimplementedKrkStopsServer struct {
}

func (*UnimplementedKrkStopsServer) GetAirly(ctx context.Context, req *Installation) (*Airly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAirly not implemented")
}
func (*UnimplementedKrkStopsServer) GetDepartures(req *Stop, srv KrkStops_GetDeparturesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDepartures not implemented")
}
func (*UnimplementedKrkStopsServer) SearchStops(req *StopSearch, srv KrkStops_SearchStopsServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchStops not implemented")
}

func RegisterKrkStopsServer(s *grpc.Server, srv KrkStopsServer) {
	s.RegisterService(&_KrkStops_serviceDesc, srv)
}

func _KrkStops_GetAirly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Installation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KrkStopsServer).GetAirly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KrkStops/GetAirly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KrkStopsServer).GetAirly(ctx, req.(*Installation))
	}
	return interceptor(ctx, in, info, handler)
}

func _KrkStops_GetDepartures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Stop)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KrkStopsServer).GetDepartures(m, &krkStopsGetDeparturesServer{stream})
}

type KrkStops_GetDeparturesServer interface {
	Send(*Departure) error
	grpc.ServerStream
}

type krkStopsGetDeparturesServer struct {
	grpc.ServerStream
}

func (x *krkStopsGetDeparturesServer) Send(m *Departure) error {
	return x.ServerStream.SendMsg(m)
}

func _KrkStops_SearchStops_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopSearch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KrkStopsServer).SearchStops(m, &krkStopsSearchStopsServer{stream})
}

type KrkStops_SearchStopsServer interface {
	Send(*Stop) error
	grpc.ServerStream
}

type krkStopsSearchStopsServer struct {
	grpc.ServerStream
}

func (x *krkStopsSearchStopsServer) Send(m *Stop) error {
	return x.ServerStream.SendMsg(m)
}

var _KrkStops_serviceDesc = grpc.ServiceDesc{
	ServiceName: "KrkStops",
	HandlerType: (*KrkStopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAirly",
			Handler:    _KrkStops_GetAirly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDepartures",
			Handler:       _KrkStops_GetDepartures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchStops",
			Handler:       _KrkStops_SearchStops_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "krkstops-grpc/krk-stops.proto",
}
