syntax = "proto3";

option go_package = "./pb";

message GetDeparturesRequest {
    string stop_name = 1;
    repeated DirectedRoute filters = 2;
}

message GetDeparturesResponse {
    repeated Departure3 departures = 1;
    repeated RouteHeadsign headsigns = 2;
}

message SearchStopsRequest {
    string query = 1;
}

message SearchStopsResponse {
    repeated string stops = 1;
}

message Filter {
    string route_id = 1;
    uint32 direction_id = 2;
}

message Departure3 {
    uint32 planned_minutes_in_day = 1;
    uint32 direction_id = 2;
    uint32 route_name = 3;
    uint32 updated_seconds_in_day = 5;
    uint32 trip_id = 6;
}

message DirectedRoute {
    uint32 route_name = 1;
    uint32 direction_id = 2;
}

message RouteHeadsign {
    repeated DirectedRoute routes = 1;
    string headsign = 2;
}
