// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: pb/krk-stops.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transit int32

const (
	Transit_BUS  Transit = 0
	Transit_TRAM Transit = 1
	Transit_ALL  Transit = 2
)

// Enum value maps for Transit.
var (
	Transit_name = map[int32]string{
		0: "BUS",
		1: "TRAM",
		2: "ALL",
	}
	Transit_value = map[string]int32{
		"BUS":  0,
		"TRAM": 1,
		"ALL":  2,
	}
)

func (x Transit) Enum() *Transit {
	p := new(Transit)
	*p = x
	return p
}

func (x Transit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transit) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_krk_stops_proto_enumTypes[0].Descriptor()
}

func (Transit) Type() protoreflect.EnumType {
	return &file_pb_krk_stops_proto_enumTypes[0]
}

func (x Transit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transit.Descriptor instead.
func (Transit) EnumDescriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{0}
}

type GetMeasurementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMeasurementRequest) Reset() {
	*x = GetMeasurementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeasurementRequest) ProtoMessage() {}

func (x *GetMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeasurementRequest.ProtoReflect.Descriptor instead.
func (*GetMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeasurementRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAirlyInstallationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAirlyInstallationRequest) Reset() {
	*x = GetAirlyInstallationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirlyInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirlyInstallationRequest) ProtoMessage() {}

func (x *GetAirlyInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirlyInstallationRequest.ProtoReflect.Descriptor instead.
func (*GetAirlyInstallationRequest) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{1}
}

func (x *GetAirlyInstallationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepartures2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDepartures2Request) Reset() {
	*x = GetDepartures2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartures2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartures2Request) ProtoMessage() {}

func (x *GetDepartures2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartures2Request.ProtoReflect.Descriptor instead.
func (*GetDepartures2Request) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{2}
}

func (x *GetDepartures2Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepartures2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Departures []*Departure `protobuf:"bytes,1,rep,name=departures,proto3" json:"departures,omitempty"`
}

func (x *GetDepartures2Response) Reset() {
	*x = GetDepartures2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartures2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartures2Response) ProtoMessage() {}

func (x *GetDepartures2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartures2Response.ProtoReflect.Descriptor instead.
func (*GetDepartures2Response) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepartures2Response) GetDepartures() []*Departure {
	if x != nil {
		return x.Departures
	}
	return nil
}

type SearchStops2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchStops2Request) Reset() {
	*x = SearchStops2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStops2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStops2Request) ProtoMessage() {}

func (x *SearchStops2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStops2Request.ProtoReflect.Descriptor instead.
func (*SearchStops2Request) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{4}
}

func (x *SearchStops2Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchStops2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stops []*Stop `protobuf:"bytes,1,rep,name=stops,proto3" json:"stops,omitempty"`
}

func (x *SearchStops2Response) Reset() {
	*x = SearchStops2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStops2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStops2Response) ProtoMessage() {}

func (x *SearchStops2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStops2Response.ProtoReflect.Descriptor instead.
func (*SearchStops2Response) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{5}
}

func (x *SearchStops2Response) GetStops() []*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

type Installation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Installation) Reset() {
	*x = Installation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Installation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Installation) ProtoMessage() {}

func (x *Installation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Installation.ProtoReflect.Descriptor instead.
func (*Installation) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{6}
}

func (x *Installation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Installation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Installation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caqi        int32   `protobuf:"varint,1,opt,name=caqi,proto3" json:"caqi,omitempty"`
	ColorStr    string  `protobuf:"bytes,2,opt,name=colorStr,proto3" json:"colorStr,omitempty"`
	Humidity    int32   `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Temperature float32 `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Color       uint32  `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{7}
}

func (x *Measurement) GetCaqi() int32 {
	if x != nil {
		return x.Caqi
	}
	return 0
}

func (x *Measurement) GetColorStr() string {
	if x != nil {
		return x.ColorStr
	}
	return ""
}

func (x *Measurement) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Measurement) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Measurement) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{8}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Departure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelativeTime       int32   `protobuf:"varint,1,opt,name=relativeTime,proto3" json:"relativeTime,omitempty"`
	PlannedTime        string  `protobuf:"bytes,2,opt,name=plannedTime,proto3" json:"plannedTime,omitempty"`
	Direction          string  `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	PatternText        string  `protobuf:"bytes,4,opt,name=patternText,proto3" json:"patternText,omitempty"`
	Color              uint32  `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	RelativeTimeParsed string  `protobuf:"bytes,6,opt,name=relativeTimeParsed,proto3" json:"relativeTimeParsed,omitempty"`
	Predicted          bool    `protobuf:"varint,7,opt,name=predicted,proto3" json:"predicted,omitempty"`
	Type               Transit `protobuf:"varint,8,opt,name=type,proto3,enum=Transit" json:"type,omitempty"`
}

func (x *Departure) Reset() {
	*x = Departure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Departure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departure) ProtoMessage() {}

func (x *Departure) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departure.ProtoReflect.Descriptor instead.
func (*Departure) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{9}
}

func (x *Departure) GetRelativeTime() int32 {
	if x != nil {
		return x.RelativeTime
	}
	return 0
}

func (x *Departure) GetPlannedTime() string {
	if x != nil {
		return x.PlannedTime
	}
	return ""
}

func (x *Departure) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Departure) GetPatternText() string {
	if x != nil {
		return x.PatternText
	}
	return ""
}

func (x *Departure) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Departure) GetRelativeTimeParsed() string {
	if x != nil {
		return x.RelativeTimeParsed
	}
	return ""
}

func (x *Departure) GetPredicted() bool {
	if x != nil {
		return x.Predicted
	}
	return false
}

func (x *Departure) GetType() Transit {
	if x != nil {
		return x.Type
	}
	return Transit_BUS
}

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id   uint32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Type Transit `protobuf:"varint,4,opt,name=type,proto3,enum=Transit" json:"type,omitempty"`
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_krk_stops_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{10}
}

func (x *Stop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stop) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stop) GetType() Transit {
	if x != nil {
		return x.Type
	}
	return Transit_BUS
}

var File_pb_krk_stops_proto protoreflect.FileDescriptor

var file_pb_krk_stops_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x6b, 0x72, 0x6b, 0x2d, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x33, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x22, 0x58, 0x0a,
	0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x71, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x71, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x22, 0x93, 0x02, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x54, 0x65,
	0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x08, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x2a, 0x25, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x52, 0x41, 0x4d, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x32, 0xc5,
	0x02, 0x0a, 0x08, 0x4b, 0x72, 0x6b, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x32, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0c, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x41, 0x69,
	0x72, 0x6c, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x09, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x79, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x32, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x32, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x32, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x74, 0x6f, 0x70, 0x73, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x32, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_krk_stops_proto_rawDescOnce sync.Once
	file_pb_krk_stops_proto_rawDescData = file_pb_krk_stops_proto_rawDesc
)

func file_pb_krk_stops_proto_rawDescGZIP() []byte {
	file_pb_krk_stops_proto_rawDescOnce.Do(func() {
		file_pb_krk_stops_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_krk_stops_proto_rawDescData)
	})
	return file_pb_krk_stops_proto_rawDescData
}

var file_pb_krk_stops_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_krk_stops_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_krk_stops_proto_goTypes = []interface{}{
	(Transit)(0),                        // 0: Transit
	(*GetMeasurementRequest)(nil),       // 1: GetMeasurementRequest
	(*GetAirlyInstallationRequest)(nil), // 2: GetAirlyInstallationRequest
	(*GetDepartures2Request)(nil),       // 3: GetDepartures2Request
	(*GetDepartures2Response)(nil),      // 4: GetDepartures2Response
	(*SearchStops2Request)(nil),         // 5: SearchStops2Request
	(*SearchStops2Response)(nil),        // 6: SearchStops2Response
	(*Installation)(nil),                // 7: Installation
	(*Measurement)(nil),                 // 8: Measurement
	(*Location)(nil),                    // 9: Location
	(*Departure)(nil),                   // 10: Departure
	(*Stop)(nil),                        // 11: Stop
}
var file_pb_krk_stops_proto_depIdxs = []int32{
	10, // 0: GetDepartures2Response.departures:type_name -> Departure
	11, // 1: SearchStops2Response.stops:type_name -> Stop
	0,  // 2: Departure.type:type_name -> Transit
	0,  // 3: Stop.type:type_name -> Transit
	1,  // 4: KrkStops.GetAirly:input_type -> GetMeasurementRequest
	9,  // 5: KrkStops.FindNearestAirlyInstallation:input_type -> Location
	2,  // 6: KrkStops.GetAirlyInstallation:input_type -> GetAirlyInstallationRequest
	3,  // 7: KrkStops.GetDepartures2:input_type -> GetDepartures2Request
	5,  // 8: KrkStops.SearchStops2:input_type -> SearchStops2Request
	8,  // 9: KrkStops.GetAirly:output_type -> Measurement
	7,  // 10: KrkStops.FindNearestAirlyInstallation:output_type -> Installation
	7,  // 11: KrkStops.GetAirlyInstallation:output_type -> Installation
	4,  // 12: KrkStops.GetDepartures2:output_type -> GetDepartures2Response
	6,  // 13: KrkStops.SearchStops2:output_type -> SearchStops2Response
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pb_krk_stops_proto_init() }
func file_pb_krk_stops_proto_init() {
	if File_pb_krk_stops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_krk_stops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeasurementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirlyInstallationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartures2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartures2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStops2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStops2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Installation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Departure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_krk_stops_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_krk_stops_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_krk_stops_proto_goTypes,
		DependencyIndexes: file_pb_krk_stops_proto_depIdxs,
		EnumInfos:         file_pb_krk_stops_proto_enumTypes,
		MessageInfos:      file_pb_krk_stops_proto_msgTypes,
	}.Build()
	File_pb_krk_stops_proto = out.File
	file_pb_krk_stops_proto_rawDesc = nil
	file_pb_krk_stops_proto_goTypes = nil
	file_pb_krk_stops_proto_depIdxs = nil
}
