// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pb/krk-stops.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeparturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopName      string                 `protobuf:"bytes,1,opt,name=stop_name,json=stopName,proto3" json:"stop_name,omitempty"`
	Filters       []*DirectedRoute       `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeparturesRequest) Reset() {
	*x = GetDeparturesRequest{}
	mi := &file_pb_krk_stops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeparturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeparturesRequest) ProtoMessage() {}

func (x *GetDeparturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeparturesRequest.ProtoReflect.Descriptor instead.
func (*GetDeparturesRequest) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeparturesRequest) GetStopName() string {
	if x != nil {
		return x.StopName
	}
	return ""
}

func (x *GetDeparturesRequest) GetFilters() []*DirectedRoute {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetDeparturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departures    []*Departure3          `protobuf:"bytes,1,rep,name=departures,proto3" json:"departures,omitempty"`
	Headsigns     []*RouteHeadsign       `protobuf:"bytes,2,rep,name=headsigns,proto3" json:"headsigns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeparturesResponse) Reset() {
	*x = GetDeparturesResponse{}
	mi := &file_pb_krk_stops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeparturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeparturesResponse) ProtoMessage() {}

func (x *GetDeparturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeparturesResponse.ProtoReflect.Descriptor instead.
func (*GetDeparturesResponse) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeparturesResponse) GetDepartures() []*Departure3 {
	if x != nil {
		return x.Departures
	}
	return nil
}

func (x *GetDeparturesResponse) GetHeadsigns() []*RouteHeadsign {
	if x != nil {
		return x.Headsigns
	}
	return nil
}

type SearchStopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStopsRequest) Reset() {
	*x = SearchStopsRequest{}
	mi := &file_pb_krk_stops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStopsRequest) ProtoMessage() {}

func (x *SearchStopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStopsRequest.ProtoReflect.Descriptor instead.
func (*SearchStopsRequest) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{2}
}

func (x *SearchStopsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchStopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stops         []string               `protobuf:"bytes,1,rep,name=stops,proto3" json:"stops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStopsResponse) Reset() {
	*x = SearchStopsResponse{}
	mi := &file_pb_krk_stops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStopsResponse) ProtoMessage() {}

func (x *SearchStopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStopsResponse.ProtoReflect.Descriptor instead.
func (*SearchStopsResponse) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{3}
}

func (x *SearchStopsResponse) GetStops() []string {
	if x != nil {
		return x.Stops
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DirectionId   uint32                 `protobuf:"varint,2,opt,name=direction_id,json=directionId,proto3" json:"direction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pb_krk_stops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{4}
}

func (x *Filter) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Filter) GetDirectionId() uint32 {
	if x != nil {
		return x.DirectionId
	}
	return 0
}

type Departure3 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlannedMinutesInDay uint32                 `protobuf:"varint,1,opt,name=planned_minutes_in_day,json=plannedMinutesInDay,proto3" json:"planned_minutes_in_day,omitempty"`
	DirectionId         uint32                 `protobuf:"varint,2,opt,name=direction_id,json=directionId,proto3" json:"direction_id,omitempty"`
	RouteName           uint32                 `protobuf:"varint,3,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	UpdatedSecondsInDay uint32                 `protobuf:"varint,5,opt,name=updated_seconds_in_day,json=updatedSecondsInDay,proto3" json:"updated_seconds_in_day,omitempty"`
	TripId              uint32                 `protobuf:"varint,6,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Departure3) Reset() {
	*x = Departure3{}
	mi := &file_pb_krk_stops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Departure3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departure3) ProtoMessage() {}

func (x *Departure3) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departure3.ProtoReflect.Descriptor instead.
func (*Departure3) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{5}
}

func (x *Departure3) GetPlannedMinutesInDay() uint32 {
	if x != nil {
		return x.PlannedMinutesInDay
	}
	return 0
}

func (x *Departure3) GetDirectionId() uint32 {
	if x != nil {
		return x.DirectionId
	}
	return 0
}

func (x *Departure3) GetRouteName() uint32 {
	if x != nil {
		return x.RouteName
	}
	return 0
}

func (x *Departure3) GetUpdatedSecondsInDay() uint32 {
	if x != nil {
		return x.UpdatedSecondsInDay
	}
	return 0
}

func (x *Departure3) GetTripId() uint32 {
	if x != nil {
		return x.TripId
	}
	return 0
}

type DirectedRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteName     uint32                 `protobuf:"varint,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	DirectionId   uint32                 `protobuf:"varint,2,opt,name=direction_id,json=directionId,proto3" json:"direction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectedRoute) Reset() {
	*x = DirectedRoute{}
	mi := &file_pb_krk_stops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectedRoute) ProtoMessage() {}

func (x *DirectedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectedRoute.ProtoReflect.Descriptor instead.
func (*DirectedRoute) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{6}
}

func (x *DirectedRoute) GetRouteName() uint32 {
	if x != nil {
		return x.RouteName
	}
	return 0
}

func (x *DirectedRoute) GetDirectionId() uint32 {
	if x != nil {
		return x.DirectionId
	}
	return 0
}

type RouteHeadsign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*DirectedRoute       `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Headsign      string                 `protobuf:"bytes,2,opt,name=headsign,proto3" json:"headsign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteHeadsign) Reset() {
	*x = RouteHeadsign{}
	mi := &file_pb_krk_stops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteHeadsign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteHeadsign) ProtoMessage() {}

func (x *RouteHeadsign) ProtoReflect() protoreflect.Message {
	mi := &file_pb_krk_stops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteHeadsign.ProtoReflect.Descriptor instead.
func (*RouteHeadsign) Descriptor() ([]byte, []int) {
	return file_pb_krk_stops_proto_rawDescGZIP(), []int{7}
}

func (x *RouteHeadsign) GetRoutes() []*DirectedRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteHeadsign) GetHeadsign() string {
	if x != nil {
		return x.Headsign
	}
	return ""
}

var File_pb_krk_stops_proto protoreflect.FileDescriptor

const file_pb_krk_stops_proto_rawDesc = "" +
	"\n" +
	"\x12pb/krk-stops.proto\"]\n" +
	"\x14GetDeparturesRequest\x12\x1b\n" +
	"\tstop_name\x18\x01 \x01(\tR\bstopName\x12(\n" +
	"\afilters\x18\x02 \x03(\v2\x0e.DirectedRouteR\afilters\"r\n" +
	"\x15GetDeparturesResponse\x12+\n" +
	"\n" +
	"departures\x18\x01 \x03(\v2\v.Departure3R\n" +
	"departures\x12,\n" +
	"\theadsigns\x18\x02 \x03(\v2\x0e.RouteHeadsignR\theadsigns\"*\n" +
	"\x12SearchStopsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"+\n" +
	"\x13SearchStopsResponse\x12\x14\n" +
	"\x05stops\x18\x01 \x03(\tR\x05stops\"F\n" +
	"\x06Filter\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12!\n" +
	"\fdirection_id\x18\x02 \x01(\rR\vdirectionId\"\xd1\x01\n" +
	"\n" +
	"Departure3\x123\n" +
	"\x16planned_minutes_in_day\x18\x01 \x01(\rR\x13plannedMinutesInDay\x12!\n" +
	"\fdirection_id\x18\x02 \x01(\rR\vdirectionId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x03 \x01(\rR\trouteName\x123\n" +
	"\x16updated_seconds_in_day\x18\x05 \x01(\rR\x13updatedSecondsInDay\x12\x17\n" +
	"\atrip_id\x18\x06 \x01(\rR\x06tripId\"Q\n" +
	"\rDirectedRoute\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\rR\trouteName\x12!\n" +
	"\fdirection_id\x18\x02 \x01(\rR\vdirectionId\"S\n" +
	"\rRouteHeadsign\x12&\n" +
	"\x06routes\x18\x01 \x03(\v2\x0e.DirectedRouteR\x06routes\x12\x1a\n" +
	"\bheadsign\x18\x02 \x01(\tR\bheadsignB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_krk_stops_proto_rawDescOnce sync.Once
	file_pb_krk_stops_proto_rawDescData []byte
)

func file_pb_krk_stops_proto_rawDescGZIP() []byte {
	file_pb_krk_stops_proto_rawDescOnce.Do(func() {
		file_pb_krk_stops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_krk_stops_proto_rawDesc), len(file_pb_krk_stops_proto_rawDesc)))
	})
	return file_pb_krk_stops_proto_rawDescData
}

var file_pb_krk_stops_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_krk_stops_proto_goTypes = []any{
	(*GetDeparturesRequest)(nil),  // 0: GetDeparturesRequest
	(*GetDeparturesResponse)(nil), // 1: GetDeparturesResponse
	(*SearchStopsRequest)(nil),    // 2: SearchStopsRequest
	(*SearchStopsResponse)(nil),   // 3: SearchStopsResponse
	(*Filter)(nil),                // 4: Filter
	(*Departure3)(nil),            // 5: Departure3
	(*DirectedRoute)(nil),         // 6: DirectedRoute
	(*RouteHeadsign)(nil),         // 7: RouteHeadsign
}
var file_pb_krk_stops_proto_depIdxs = []int32{
	6, // 0: GetDeparturesRequest.filters:type_name -> DirectedRoute
	5, // 1: GetDeparturesResponse.departures:type_name -> Departure3
	7, // 2: GetDeparturesResponse.headsigns:type_name -> RouteHeadsign
	6, // 3: RouteHeadsign.routes:type_name -> DirectedRoute
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_krk_stops_proto_init() }
func file_pb_krk_stops_proto_init() {
	if File_pb_krk_stops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_krk_stops_proto_rawDesc), len(file_pb_krk_stops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_krk_stops_proto_goTypes,
		DependencyIndexes: file_pb_krk_stops_proto_depIdxs,
		MessageInfos:      file_pb_krk_stops_proto_msgTypes,
	}.Build()
	File_pb_krk_stops_proto = out.File
	file_pb_krk_stops_proto_goTypes = nil
	file_pb_krk_stops_proto_depIdxs = nil
}
